## WiSHFUL Agent config file

agent_info:
  name: 'agent_envemu'
  info: 'agent_envemu'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_envemu"}

  module_envemu:
      module : wishful_module_envemu
      class_name : EnvEmuModule
      interfaces : ['ee']
